Update sbackres

diff --git a/105/sbackres b/105/sbackres
--- a/105/sbackres
+++ b/105/sbackres
@@ -3,19 +3,28 @@
 
 dir_should_be_backuped_path=/;
 dir_should_be_backuped_name=temp
-where_saved_backup=/home/hosein/backup;
+where_saved_backup=/home/${USER}/backup;
 #tarfile_name="etc000$(date +%F%T)";
 backup_file_name="etc-$(date +%F%T)";
 
+LOG_FILE="/home/${USER}/b.log"
 
 #crontab -l | { cat; echo "*/1 * * * * touch /home/hosein/test/a.txt"; } | crontab -
 
 
+log ()
+{
+	echo "$1"
+	echo "$1" >> $LOG_FILE
+}
+
+log "-------$(date +%d-%m-%Y-%H%M%S)------" 
+
 
 function backup {
-  echo " i am function for backup" ;
-  printf "option backup used \n"
-      printf "creating archive ...... \n> "
+  log " i am function for backup" ;
+  log "option backup used \n"
+      log "creating archive ...... \n> "
 
       #tar -cvf  a.tar /etc > /dev/null;
 
@@ -24,42 +33,42 @@ function backup {
       
 
       if [ $? -eq 0 ]; then
-	      echo “create archive step successfully done”;
-        echo "backup $backup_file_name is created and stored in $where_saved_backup";
+	      log “create archive step successfully done”;
+        log "backup $backup_file_name is created and stored in $where_saved_backup";
         
       else
-        echo 'create archive step failed | please contact admin' 
+        log 'create archive step failed | please contact admin' 
         exit
       fi
 
 
-      printf "compressing $where_saved_backup/$backup_file_name.tar' ...... \n> "
+      log "compressing $where_saved_backup/$backup_file_name.tar' ...... \n> "
       gzip  $where_saved_backup/$backup_file_name.tar;
       echo -n "secret" | openssl aes-256-cbc -a -salt -pbkdf2 -in $where_saved_backup/$backup_file_name.tar.gz -out "$where_saved_backup/$backup_file_name.tar.gz.enc"   -pass stdin
       rm -rf $where_saved_backup/$backup_file_name.tar.gz ;
 
 
-      echo "successfuly backup file created from $dir_should_be_backuped_path$dir_should_be_backuped_name  and backup file saved in $where_saved_backup with name of $backup_file_name ";
+      log "successfuly backup file created from $dir_should_be_backuped_path$dir_should_be_backuped_name  and backup file saved in $where_saved_backup with name of $backup_file_name ";
 
 }
 
 
 
 function restore {
-  echo " i am function for restore" ;
+  log " i am function for restore" ;
 
         
-      printf "option restore used \n\n"
+      log "option restore used \n\n"
      
 
 
 
       if [ -n "$(ls -A $where_saved_backup 2>/dev/null)" ]
       then
-        printf "available backups to restore \n\n"
+        log "available backups to restore \n\n"
         b=$(ls $where_saved_backup );
-        echo "$b \n\n"
-        printf "please select one of them (enter one of them name ) :> "
+        log "$b \n\n"
+        log "please select one of them (enter one of them name ) :> "
 
         read selected_backup_file;
         
@@ -68,13 +77,13 @@ function restore {
         if [ -e "$where_saved_backup/$selected_backup_file" ]; then
           
          
-          echo '*************************';
+          log '*************************';
 
 
 
 
 
-          echo "extracting $selected_backup_file  to  ./  ......";
+          log "extracting $selected_backup_file  to  ./  ......";
 
           echo -n "secret" | openssl aes-256-cbc -d -a -pbkdf2 -in "$where_saved_backup/$selected_backup_file" -out ${selected_backup_file%.*}  -pass stdin
           
@@ -84,16 +93,16 @@ function restore {
 
 
           if [ $? -eq 0 ]; then
-	          echo “extracting backup  successfully done”
+	          log “extracting backup  successfully done”
           else
-            echo 'extracting backup failed | please contact admin' 
+            log 'extracting backup failed | please contact admin' 
             exit
           fi
 
 
+          
 
-
-          echo " restore process started "
+          log " restore process started "
           rsync -a "./$dir_should_be_backuped_name/" "$dir_should_be_backuped_path$dir_should_be_backuped_name" --delete
 
           rm -rf "./${selected_backup_file%.gz*}" ;
@@ -101,11 +110,14 @@ function restore {
 
 
           if [ $? -eq 0 ]; then
-	          echo “restoring backup  successfully done”
+	          log “restoring1 backup  successfully done”
           else
-            echo 'restoring backup failed | please contact admin' 
-            exit
+            log 'restoring2 backup failed | please contact admin' 
+            
           fi
+
+
+          
 
 
 
@@ -114,13 +126,13 @@ function restore {
           
 
         else 
-          echo "you enter a backupfile that dont exist at all"
+          log "you enter a backupfile that dont exist at all"
           exit
         fi 
 
         
       else
-        echo "there is no backupfile to  restore to it "
+        log "there is no backupfile to  restore to it "
         exit
       fi
 
@@ -139,21 +151,21 @@ function restore {
 if [[ $1 == "" ]] #Where "$1" is the positional argument you want to validate 
 
  then
-  echo "interactive mode activated "
-  printf "do you want get backup or restore ? (b for backup . r for restore) \n\n"
+  log "interactive mode activated "
+  log "do you want get backup or restore ? (b for backup . r for restore) \n\n"
   read action;
 
   
 
   if [ $action == 'b' ] || [ $action == 'r' ]; then
-    if [ $action == 'b' ]; then echo 'backup selected' 
+    if [ $action == 'b' ]; then log 'backup selected' 
       backup;
     fi 
-    if [ $action == 'r' ]; then echo 'restore selected' 
+    if [ $action == 'r' ]; then log 'restore selected' 
       restore;
     fi 
   else
-    echo “invalid option passed”
+    log “invalid option passed”
   fi
 
 
@@ -168,6 +180,10 @@ while getopts :br OPT; do
     b)
 
       backup
+
+      log "`date -u` backup completed with exit code $?" 
+      log "----------------------------------------------" 
+
       
 
       ;;
@@ -175,9 +191,13 @@ while getopts :br OPT; do
 
       restore
 
+      log "`date -u` restore process completed with exit code $?" 
+      log "----------------------------------------------" 
+
+
       ;;
     ?)
-      echo " option invalid ${OPTARG} "
+      log " option invalid ${OPTARG} "
       ;;
   esac
 done
