Update snginx

diff --git a/105/snginx b/105/snginx
--- a/105/snginx
+++ b/105/snginx
@@ -1,41 +1,80 @@
 #!/bin/bash
 
-echo 'hi'; 
 
-
-#crontab -l | { cat; echo "0 */72 * * * touch /home/hosein/test/a.txt"; } | crontab -
-
-file_path=/var/log/nginx/access.log;
-file_name="access_$(date +%F).log.tar";
-path=/var/log/nginx; 
-#tar -cfv "${file_name} $file_path";
-#tar -cfv  a.tar /var/log/nginx/access.log;
-#tar -cvf  $path/$file_name $file_path;  #-cvf vs -cfv  fargh daran  ; avali doroste
+# ----------------------------------------------------------------------
+# name:         snginx.sh
+# version:      1.0
+# createTime:   2024-06-04
+# description:  if /var/log/access.log file exceed 200Mb . archive it
+# author:       muedsa
+# ----------------------------------------------------------------------
 
 
 
-#if [ -n "$(find ${file_path} -size +200M)" ]; then
-if [ -n "$(find ${file_path} -size +1k)" ]; then
-    printf '%s is strictly larger than 100kb\n' "$file_path";
-
-    #cp $file_path $path/$file_name;
-    #echo "" > $file_path;
 
 
-    #tar -cvf  $path/$file_name $file_path;
+TARGET_FILE="/var/log/nginx/access.log"
+TARGET_FILE_PATH="/var/log/nginx"
+TARGET_FILE_NAME="access.log"
 
-    touch "$path/$file_name";
+BACKUP_SAVE_PATH='/var/log/nginx/'
+BACKUP_FILE_NAME=access_$(date '+%Y%m%d').log.tar
+#this is log file for this script
+LOG_FILE="/home/${USER}/a.log"
+
+LOG_MAX_FILE_SIZE=1k  #100M
+
+NGINX_PID=/var/run/nginx.pid
+
+#touch $LOG_FILE;
+
+
+log ()
+{
+	echo "$1"
+	echo "$1" >> $LOG_FILE
+}
+log "------Backup-$(date +%d-%m-%Y-%H%M%S)------" 
+
+
+#check target file exist or not
+if [ -e "$TARGET_FILE_PATH/$TARGET_FILE_NAME" ]; then
+    log "target file for backup exist we can edame the process"
+else 
+    log "target file dont exist"
+    exit;
+fi 
+
+
+
+if [ -n "$(find ${TARGET_FILE} -size +${LOG_MAX_FILE_SIZE})" ]; then
+
+    log "$TARGET_FILE is strictly larger than ${LOG_MAX_FILE_SIZE} so we archive it";
+
+
     
-    tar -cvf  "$path/$file_name" $file_path;
-    echo "" > $file_path;
-    #rm -rf $file_path;
-   # touch $file_path;
-    #kill -HUP `cat /var/run/nginx.pid`
+    touch "${BACKUP_SAVE_PATH}/${BACKUP_FILE_NAME}";
 
-    #tar -xf a.log.tar --dir b.log
+
+    log "create archive file -->  ${BACKUP_SAVE_PATH}/${BACKUP_FILE_NAME}";
+    cd $TARGET_FILE_PATH && tar -cPf "${BACKUP_SAVE_PATH}/${BACKUP_FILE_NAME}"  $TARGET_FILE_NAME;
+
+
+
+    if [ $? -eq 0 ]; then
+        log "create archive successfully done"
+    else 
+        log "create archive step failed | please contact admin"
+        exit;
+    fi 
+
+    log "make empty access.log file "
+    echo "" > "$TARGET_FILE_PATH/$TARGET_FILE_NAME"
 
 fi
 
 
+log "`date -u` backup completed with exit code $?" 
+log "----------------------------------------------" 
 
 
